require("entity-functions")

local MODNAME = "__SenpaisOverhall__"

data:extend
(
{
 {
  type = "particle",
  name = "ls-particles",
  flags = {"not-on-map"},
  life_time = 180,
  pictures = {
              { filename = MODNAME.."/graphics/entitys/ore-particle-1.png", priority = "extra-high", width = 5, height = 5, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-2.png", priority = "extra-high", width = 7, height = 5, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-3.png", priority = "extra-high", width = 6, height = 7, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-4.png", priority = "extra-high", width = 9, height = 8, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-5.png", priority = "extra-high", width = 5, height = 5, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-6.png", priority = "extra-high", width = 6, height = 4, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-7.png", priority = "extra-high", width = 7, height = 8, frame_count = 1 },
              { filename = MODNAME.."/graphics/entitys/ore-particle-8.png", priority = "extra-high", width = 6, height = 5, frame_count = 1 }
             },
  shadows = {
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-1.png", priority = "extra-high", width = 5, height = 5, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-2.png", priority = "extra-high", width = 7, height = 5, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-3.png", priority = "extra-high", width = 6, height = 7, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-4.png", priority = "extra-high", width = 9, height = 8, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-5.png", priority = "extra-high", width = 5, height = 5, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-6.png", priority = "extra-high", width = 6, height = 4, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-7.png", priority = "extra-high", width = 7, height = 8, frame_count = 1 },
             { filename = MODNAME.."/graphics/entitys/ore-particle-shadow-8.png", priority = "extra-high", width = 6, height = 5, frame_count = 1 },
            }
 },
 {
  type = "resource",
  name = "angel-ore",
  icon = MODNAME.."/graphics/icons/angel-ore.png",
  flags = {"placeable-neutral"},
  order="a-b-a",
  minable = { hardness = 4, mining_particle = "ls-particles", mining_time = 2, result = "angel-ore" },
  collision_box = {{ -0.1, -0.1}, {0.1, 0.1}},
  selection_box = {{ -0.5, -0.5}, {0.5, 0.5}},
  autoplace = { control = "angel-ore", sharpness = 0.99, max_probability = 0.035, richness_base = 100, richness_multiplier = 1, richness_multiplier_distance_bonus = 10, coverage = 0.05,
  				      peaks = { { noise_layer = "angel-ore", noise_octaves_difference = -1, noise_persistence = 0.4, } } },
  stage_counts = {10},
  stages = { sheet = { filename = MODNAME.."/graphics/entitys/angel-ore.png", priority = "extra-high", width = 38, height = 38, frame_count = 4, variation_count = 8 } },
  map_color = {r = 217, g = 220, b = 219},
 },
 {
  type = "resource",
  name = "devil-ore",
  icon = MODNAME.."/graphics/icons/devil-ore.png",
  flags = {"placeable-neutral"},
  order="a-b-a",
  minable = { hardness = 4, mining_particle = "ls-particles", mining_time = 2, result = "devil-ore" },
  collision_box = {{ -0.1, -0.1}, {0.1, 0.1}},
  selection_box = {{ -0.5, -0.5}, {0.5, 0.5}},
  autoplace = { control = "devil-ore", sharpness = 0.99, max_probability = 0.035, richness_base = 100, richness_multiplier = 1, richness_multiplier_distance_bonus = 10, coverage = 0.05,
  				      peaks = { { noise_layer = "devil-ore", noise_octaves_difference = -1, noise_persistence = 0.4, } } },
  stage_counts = {10},
  stages = { sheet = { filename = MODNAME.."/graphics/entitys/devil-ore.png", priority = "extra-high", width = 38, height = 38, frame_count = 4, variation_count = 8 } },
  map_color = {r = 137, g = 130, b = 130},
 },
 {
  type = "resource",
  name = "bavarium",
  icon = MODNAME.."/graphics/icons/bavarium.png",
  flags = {"placeable-neutral"},
  order="a-b-a",
  minable = { hardness = 3, mining_particle = "ls-particles", mining_time = 2, result = "bavarium" },
  collision_box = {{ -0.1, -0.1}, {0.1, 0.1}},
  selection_box = {{ -0.5, -0.5}, {0.5, 0.5}},
  autoplace = { control = "bavarium", sharpness = 1, richness_multiplier = 1500, richness_multiplier_distance_bonus = 20, richness_base = 500, coverage = 0.02, 
  				peaks = { { noise_layer = "bavarium", noise_octaves_difference = -1.5, noise_persistence = 0.3, starting_area_weight_optimal = 0, starting_area_weight_range = 0, starting_area_weight_max_range = 2 },
  						  { noise_layer = "bavarium", noise_octaves_difference = -2, noise_persistence = 0.3, starting_area_weight_optimal = 1, starting_area_weight_range = 0, starting_area_weight_max_range = 2 },
      					  { influence = 0.15 + 0, starting_area_weight_optimal = 1, starting_area_weight_range = 0, starting_area_weight_max_range = 2 } } },
  stage_counts = {1000, 600, 400, 200, 100, 50, 20, 1},
  stages = { sheet = { filename = MODNAME.."/graphics/entitys/bavarium.png", priority = "extra-high", width = 38, height = 38, frame_count = 4, variation_count = 8 } },
  map_color = {r = 9, g = 164, b = 149}
 },
 {
  type = "generator",
  name = "steam-2",
  icon = MODNAME.."/graphics/icons/steam-2.png",
  flags = { "placeable-neutral","player-creation" },
  minable = { mining_time = 1, result = "steam-2" },
  max_health = 600,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  effectivity = 2,
  fluid_usage_per_tick = 0.1,
  resistances = { { type = "fire", percent = 70 } },
  collision_box = { {-1.35, -2.35}, {1.35, 2.35} },
  selection_box = { {-1.5, -2.5}, {1.5, 2.5} },
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = { 0, 3 } }, { position = { 0, -3 } } } },
  energy_source = { type = "electric", usage_priority = "secondary-output" },
  horizontal_animation = { filename = MODNAME.."/graphics/entitys/steam-hori-2.png", width = 246, height = 137, frame_count = 32, line_length = 8, shift = { 1.34, -0.06 } },
  vertical_animation = { filename = MODNAME.."/graphics/entitys/steam-verti-2.png", width = 155, height = 186, frame_count = 32, line_length = 8, shift = { 0.812, 0.03125 } },
  smoke = { { name = "light-smoke", north_position = { 0.9, 0.0 }, east_position = { -2.0, -2.0 }, frequency = 10 / 32, starting_vertical_speed = 0.08, slow_down_factor = 1, starting_frame_deviation = 60 } },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/steam-engine-90bpm.ogg", volume = 0.6 }, match_speed_to_activity = true, },
  min_perceived_performance = 0.25,
  performance_to_sound_speedup = 0.5
 },
 {
  type = "generator",
  name = "steam-3",
  icon = MODNAME.."/graphics/icons/steam-3.png",
  flags = { "placeable-neutral","player-creation" },
  minable = { mining_time = 1, result = "steam-3" },
  max_health = 900,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  effectivity = 3,
  fluid_usage_per_tick = 0.1,
  resistances = { { type = "fire", percent = 70 } },
  collision_box = { {-1.35, -2.35}, {1.35, 2.35} },
  selection_box = { {-1.5, -2.5}, {1.5, 2.5} },
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = { 0, 3 } }, { position = { 0, -3 } } } },
  energy_source = { type = "electric", usage_priority = "secondary-output" },
  horizontal_animation = { filename = MODNAME.."/graphics/entitys/steam-hori-3.png", width = 246, height = 137, frame_count = 32, line_length = 8, shift = { 1.34, -0.06 } },
  vertical_animation = { filename = MODNAME.."/graphics/entitys/steam-verti-3.png", width = 155, height = 186, frame_count = 32, line_length = 8, shift = { 0.812, 0.03125 } },
  smoke = { { name = "light-smoke", north_position = { 0.9, 0.0 }, east_position = { -2.0, -2.0 }, frequency = 10 / 32, starting_vertical_speed = 0.08, slow_down_factor = 1, starting_frame_deviation = 60 } },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/steam-engine-90bpm.ogg", volume = 0.6 }, match_speed_to_activity = true, },
  min_perceived_performance = 0.25,
  performance_to_sound_speedup = 0.5
 },
 {
  type = "generator",
  name = "steam-4",
  icon = MODNAME.."/graphics/icons/steam-4.png",
  flags = { "placeable-neutral","player-creation" },
  minable = { mining_time = 1, result = "steam-4" },
  max_health = 1200,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  effectivity = 4,
  fluid_usage_per_tick = 0.1,
  resistances = { { type = "fire", percent = 70 } },
  collision_box = { {-1.35, -2.35}, {1.35, 2.35} },
  selection_box = { {-1.5, -2.5}, {1.5, 2.5} },
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = { 0, 3 } }, { position = { 0, -3 } } } },
  energy_source = { type = "electric", usage_priority = "secondary-output" },
  horizontal_animation = { filename = MODNAME.."/graphics/entitys/steam-hori-4.png", width = 246, height = 137, frame_count = 32, line_length = 8, shift = { 1.34, -0.06 } },
  vertical_animation = { filename = MODNAME.."/graphics/entitys/steam-verti-4.png", width = 155, height = 186, frame_count = 32, line_length = 8, shift = { 0.812, 0.03125 } },
  smoke = { { name = "light-smoke", north_position = { 0.9, 0.0 }, east_position = { -2.0, -2.0 }, frequency = 10 / 32, starting_vertical_speed = 0.08, slow_down_factor = 1, starting_frame_deviation = 60 } },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/steam-engine-90bpm.ogg", volume = 0.6 }, match_speed_to_activity = true },
  min_perceived_performance = 0.25,
  performance_to_sound_speedup = 0.5
 },
 {
  type = "generator",
  name = "steam-5",
  icon = MODNAME.."/graphics/icons/steam-5.png",
  flags = { "placeable-neutral","player-creation" },
  minable = { mining_time = 1, result = "steam-5" },
  max_health = 1500,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  effectivity = 5,
  fluid_usage_per_tick = 0.1,
  resistances = { { type = "fire", percent = 70 } },
  collision_box = { {-1.35, -2.35}, {1.35, 2.35} },
  selection_box = { {-1.5, -2.5}, {1.5, 2.5} },
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = { 0, 3 } }, { position = { 0, -3 } } } },
  energy_source = { type = "electric", usage_priority = "secondary-output" },
  horizontal_animation = { filename = MODNAME.."/graphics/entitys/steam-hori-5.png", width = 246, height = 137, frame_count = 32, line_length = 8, shift = { 1.34, -0.06 } },
  vertical_animation = { filename = MODNAME.."/graphics/entitys/steam-verti-5.png", width = 155, height = 186, frame_count = 32, line_length = 8, shift = { 0.812, 0.03125 } },
  smoke = { { name = "light-smoke", north_position = { 0.9, 0.0 }, east_position = { -2.0, -2.0 }, frequency = 10 / 32, starting_vertical_speed = 0.08, slow_down_factor = 1, starting_frame_deviation = 60 } },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/steam-engine-90bpm.ogg", volume = 0.6 }, match_speed_to_activity = true, },
  min_perceived_performance = 0.25,
  performance_to_sound_speedup = 0.5
 },
 {
  type = "boiler",
  name = "boiler-2",
  icon = MODNAME.."/graphics/icons/boiler-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "boiler-2"},
  max_health = 200,
  corpse = "small-remnants",
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  resistances = { { type = "fire", percent = 80 } },
  fast_replaceable_group = "pipe",
  collision_box = {{-0.29, -0.29}, {0.29, 0.29}},
  selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = {0, -1} }, { position = {1, 0} }, { position = {0, 1} }, { position = {-1, 0} } } },
  energy_consumption = "350kW",
  burner = { effectivity = 1, fuel_inventory_size = 2, emissions = 0.1 / 6.0, smoke = { { name = "smoke", position = {0.0, -0.8}, frequency = 5, starting_vertical_speed = 0.0, starting_frame_deviation = 60 } } },
  working_sound = { sound = { filename = "__base__/sound/boiler.ogg", volume = 0.8 }, max_sounds_per_type = 3 },
  structure = {
          left = { filename = MODNAME.."/graphics/entitys/boiler-left-2.png", priority = "extra-high", width = 46, height = 46, shift = {0.03125, 0} },
        down = { filename = MODNAME.."/graphics/entitys/boiler-down-2.png", priority = "extra-high", width = 66, height = 72 },
        left_down = { filename = MODNAME.."/graphics/entitys/boiler-left-down-2.png", priority = "extra-high", width = 60, height = 50 },
        right_down = { filename = MODNAME.."/graphics/entitys/boiler-right-down-2.png", priority = "extra-high", width = 44, height = 50 },
        left_up = { filename = MODNAME.."/graphics/entitys/boiler-left-up-2.png", priority = "extra-high", width = 66, height = 74 },
        right_up = { filename = MODNAME.."/graphics/entitys/boiler-right-up-2.png", priority = "extra-high", width = 46, height = 72 },
        t_down = { filename = MODNAME.."/graphics/entitys/boiler-t-down-2.png", priority = "extra-high", width = 44, height = 50 },
        t_up = { filename = MODNAME.."/graphics/entitys/boiler-t-up-2.png", priority = "extra-high", width = 46, height = 70 }
        },
  fire = { left = boilerfires.down, down = boilerfires.left, left_down = boilerfires.right, right_down = boilerfires.left, left_up = boilerfires.down, right_up = boilerfires.down, t_up = boilerfires.down },
  burning_cooldown = 20,
  pictures = pipepictures()
  },
  {
  type = "boiler",
  name = "boiler-3",
  icon = MODNAME.."/graphics/icons/boiler-3.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "boiler-3"},
  max_health = 300,
  corpse = "small-remnants",
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  resistances = { { type = "fire", percent = 80 } },
  fast_replaceable_group = "pipe",
  collision_box = {{-0.29, -0.29}, {0.29, 0.29}},
  selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = {0, -1} }, { position = {1, 0} }, { position = {0, 1} }, { position = {-1, 0} } } },
  energy_consumption = "310kW",
  burner = { effectivity = 1.5, fuel_inventory_size = 3, emissions = 0.1 / 5.5, smoke = { { name = "smoke", position = {0.0, -0.8}, frequency = 5, starting_vertical_speed = 0.0, starting_frame_deviation = 60 } } },
  working_sound = { sound = { filename = "__base__/sound/boiler.ogg", volume = 0.8 }, max_sounds_per_type = 3 },
  structure = {
          left = { filename = MODNAME.."/graphics/entitys/boiler-left-3.png", priority = "extra-high", width = 46, height = 46, shift = {0.03125, 0} },
        down = { filename = MODNAME.."/graphics/entitys/boiler-down-3.png", priority = "extra-high", width = 66, height = 72 },
        left_down = { filename = MODNAME.."/graphics/entitys/boiler-left-down-3.png", priority = "extra-high", width = 60, height = 50 },
        right_down = { filename = MODNAME.."/graphics/entitys/boiler-right-down-3.png", priority = "extra-high", width = 44, height = 50 },
        left_up = { filename = MODNAME.."/graphics/entitys/boiler-left-up-3.png", priority = "extra-high", width = 66, height = 74 },
        right_up = { filename = MODNAME.."/graphics/entitys/boiler-right-up-3.png", priority = "extra-high", width = 46, height = 72 },
        t_down = { filename = MODNAME.."/graphics/entitys/boiler-t-down-3.png", priority = "extra-high", width = 44, height = 50 },
        t_up = { filename = MODNAME.."/graphics/entitys/boiler-t-up-3.png", priority = "extra-high", width = 46, height = 70 }
        },
  fire = { left = boilerfires.down, down = boilerfires.left, left_down = boilerfires.right, right_down = boilerfires.left, left_up = boilerfires.down, right_up = boilerfires.down, t_up = boilerfires.down },
  burning_cooldown = 20,
  pictures = pipepictures()
  },
  {
  type = "boiler",
  name = "boiler-4",
  icon = MODNAME.."/graphics/icons/boiler-4.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "boiler-4"},
  max_health = 400,
  corpse = "small-remnants",
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  resistances = { { type = "fire", percent = 80 } },
  fast_replaceable_group = "pipe",
  collision_box = {{-0.29, -0.29}, {0.29, 0.29}},
  selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = {0, -1} }, { position = {1, 0} }, { position = {0, 1} }, { position = {-1, 0} } } },
  energy_consumption = "270kW",
  burner = { effectivity = 2, fuel_inventory_size = 4, emissions = 0.1 / 5.0, smoke = { { name = "smoke", position = {0.0, -0.8}, frequency = 5, starting_vertical_speed = 0.0, starting_frame_deviation = 60 } } },
  working_sound = { sound = { filename = "__base__/sound/boiler.ogg", volume = 0.8 }, max_sounds_per_type = 3 },
  structure = {
          left = { filename = MODNAME.."/graphics/entitys/boiler-left-4.png", priority = "extra-high", width = 46, height = 46, shift = {0.03125, 0} },
        down = { filename = MODNAME.."/graphics/entitys/boiler-down-4.png", priority = "extra-high", width = 66, height = 72 },
        left_down = { filename = MODNAME.."/graphics/entitys/boiler-left-down-4.png", priority = "extra-high", width = 60, height = 50 },
        right_down = { filename = MODNAME.."/graphics/entitys/boiler-right-down-4.png", priority = "extra-high", width = 44, height = 50 },
        left_up = { filename = MODNAME.."/graphics/entitys/boiler-left-up-4.png", priority = "extra-high", width = 66, height = 74 },
        right_up = { filename = MODNAME.."/graphics/entitys/boiler-right-up-4.png", priority = "extra-high", width = 46, height = 72 },
        t_down = { filename = MODNAME.."/graphics/entitys/boiler-t-down-4.png", priority = "extra-high", width = 44, height = 50 },
        t_up = { filename = MODNAME.."/graphics/entitys/boiler-t-up-4.png", priority = "extra-high", width = 46, height = 70 }
        },
  fire = { left = boilerfires.down, down = boilerfires.left, left_down = boilerfires.right, right_down = boilerfires.left, left_up = boilerfires.down, right_up = boilerfires.down, t_up = boilerfires.down },
  burning_cooldown = 20,
  pictures = pipepictures()
  },
  {
  type = "boiler",
  name = "boiler-5",
  icon = MODNAME.."/graphics/icons/boiler-5.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "boiler-5"},
  max_health = 500,
  corpse = "small-remnants",
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  resistances = { { type = "fire", percent = 80 } },
  fast_replaceable_group = "pipe",
  collision_box = {{-0.29, -0.29}, {0.29, 0.29}},
  selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
  fluid_box = { base_area = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { position = {0, -1} }, { position = {1, 0} }, { position = {0, 1} }, { position = {-1, 0} } } },
  energy_consumption = "230kW",
  burner = { effectivity = 2.5, fuel_inventory_size = 5, emissions = 0.1 / 4.5, smoke = { { name = "smoke", position = {0.0, -0.8}, frequency = 5, starting_vertical_speed = 0.0, starting_frame_deviation = 60 } } },
  working_sound = { sound = { filename = "__base__/sound/boiler.ogg", volume = 0.8 }, max_sounds_per_type = 3 },
  structure = {
          left = { filename = MODNAME.."/graphics/entitys/boiler-left-5.png", priority = "extra-high", width = 46, height = 46, shift = {0.03125, 0} },
        down = { filename = MODNAME.."/graphics/entitys/boiler-down-5.png", priority = "extra-high", width = 66, height = 72 },
        left_down = { filename = MODNAME.."/graphics/entitys/boiler-left-down-5.png", priority = "extra-high", width = 60, height = 50 },
        right_down = { filename = MODNAME.."/graphics/entitys/boiler-right-down-5.png", priority = "extra-high", width = 44, height = 50 },
        left_up = { filename = MODNAME.."/graphics/entitys/boiler-left-up-5.png", priority = "extra-high", width = 66, height = 74 },
        right_up = { filename = MODNAME.."/graphics/entitys/boiler-right-up-5.png", priority = "extra-high", width = 46, height = 72 },
        t_down = { filename = MODNAME.."/graphics/entitys/boiler-t-down-5.png", priority = "extra-high", width = 44, height = 50 },
        t_up = { filename = MODNAME.."/graphics/entitys/boiler-t-up-5.png", priority = "extra-high", width = 46, height = 70 }
        },
  fire = { left = boilerfires.down, down = boilerfires.left, left_down = boilerfires.right, right_down = boilerfires.left, left_up = boilerfires.down, right_up = boilerfires.down, t_up = boilerfires.down },
  burning_cooldown = 20,
  pictures = pipepictures()
 },
 {
  type = "solar-panel",
  name = "solar-2",
  icon = MODNAME.."/graphics/icons/solar-2.png",
  flags = { "placeable-neutral", "player-creation" },
  minable = { hardness = 0.2, mining_time = 0.5, result = "solar-2" },
  max_health = 200,
  corpse = "big-remnants",
  collision_box = { { -1.4, -1.4}, {1.4, 1.4 } },
  selection_box = { {-1.5, -1.5}, {1.5, 1.5} },
  energy_source = { type = "electric", usage_priority = "solar" },
  picture = { filename = MODNAME.."/graphics/entitys/solar-2.png", priority = "high", width = 104, height = 96 },
  production = "120kW"
 },
 {
  type = "solar-panel",
  name = "solar-3",
  icon = MODNAME.."/graphics/icons/solar-3.png",
  flags = { "placeable-neutral", "player-creation" },
  minable = { hardness = 0.2, mining_time = 0.5, result = "solar-3" },
  max_health = 300,
  corpse = "big-remnants",
  collision_box = { { -1.4, -1.4}, {1.4, 1.4 } },
  selection_box = { { -1.5, -1.5}, {1.5, 1.5 } },
  energy_source = { type = "electric", usage_priority = "solar" },
  picture = { filename = MODNAME.."/graphics/entitys/solar-3.png", priority = "high", width = 104, height = 96 },
  production = "180kW"
 },
 {
  type = "solar-panel",
  name = "solar-4",
  icon = MODNAME.."/graphics/icons/solar-4.png",
  flags = { "placeable-neutral", "player-creation" },
  minable = { hardness = 0.2, mining_time = 0.5, result = "solar-4" },
  max_health = 400,
  corpse = "big-remnants",
  collision_box = {{-1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  energy_source = { type = "electric", usage_priority = "solar" },
  picture = { filename = MODNAME.."/graphics/entitys/solar-4.png", priority = "high", width = 104, height = 96 },
  production = "240kW"
 },
 {
  type = "solar-panel",
  name = "solar-5",
  icon = MODNAME.."/graphics/icons/solar-5.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "solar-5"},
  max_health = 500,
  corpse = "big-remnants",
  collision_box = {{-1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  energy_source = { type = "electric", usage_priority = "solar" },
  picture = { filename = MODNAME.."/graphics/entitys/solar-5.png", priority = "high", width = 104, height = 96 },
  production = "300kW"
 },
 {
  type = "accumulator",
  name = "accu-2",
  icon = MODNAME.."/graphics/icons/accu-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "accu-2"},
  max_health = 300,
  corpse = "medium-remnants",
  collision_box = {{-0.9, -0.9}, {0.9, 0.9}},
  selection_box = {{-1, -1}, {1, 1}},
  energy_source =
  { type = "electric", buffer_capacity = "10MJ", usage_priority = "terciary", input_flow_limit = "600kW", output_flow_limit = "600kW" },
  picture = { filename = MODNAME.."/graphics/entitys/accu-2.png", priority = "extra-high", width = 124, height = 103, shift = {0.6875, -0.203125} },
  charge_animation = { filename = MODNAME.."/graphics/entitys/accu-charge-2.png", width = 138, height = 135, line_length = 8, frame_count = 24, shift = {0.46875, -0.640625}, animation_speed = 0.5 },
  charge_cooldown = 30,
  charge_light = {intensity = 0.3, size = 7},
  discharge_animation = { filename = MODNAME.."/graphics/entitys/accu-discharge-2.png", width = 147, height = 128, line_length = 8, frame_count = 24, shift = {0.390625, -0.53125}, animation_speed = 0.5 },
  discharge_cooldown = 60,
  discharge_light = {intensity = 0.7, size = 7},
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 5 },
  circuit_wire_connection_point = { shadow = { red = {0.984375, 1.10938}, green = {0.890625, 1.10938} }, wire = { red = {0.6875, 0.59375}, green = {0.6875, 0.71875} } },
  circuit_connector_sprites = get_circuit_connector_sprites({0.46875, 0.5}, {0.46875, 0.8125}, 26),
  circuit_wire_max_distance = 7.5,
  default_output_signal = "signal-A"
 },
 {
  type = "accumulator",
  name = "accu-3",
  icon = MODNAME.."/graphics/icons/accu-3.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "accu-3"},
  max_health = 450,
  corpse = "medium-remnants",
  collision_box = {{-0.9, -0.9}, {0.9, 0.9}},
  selection_box = {{-1, -1}, {1, 1}},
  energy_source =
  { type = "electric", buffer_capacity = "15MJ", usage_priority = "terciary", input_flow_limit = "900kW", output_flow_limit = "900kW" },
  picture = { filename = MODNAME.."/graphics/entitys/accu-3.png", priority = "extra-high", width = 124, height = 103, shift = {0.6875, -0.203125} },
  charge_animation = { filename = MODNAME.."/graphics/entitys/accu-charge-3.png", width = 138, height = 135, line_length = 8, frame_count = 24, shift = {0.46875, -0.640625}, animation_speed = 0.5 },
  charge_cooldown = 30,
  charge_light = {intensity = 0.3, size = 7},
  discharge_animation = { filename = MODNAME.."/graphics/entitys/accu-discharge-3.png", width = 147, height = 128, line_length = 8, frame_count = 24, shift = {0.390625, -0.53125}, animation_speed = 0.5 },
  discharge_cooldown = 60,
  discharge_light = {intensity = 0.7, size = 7},
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 5 },
  circuit_wire_connection_point = { shadow = { red = {0.984375, 1.10938}, green = {0.890625, 1.10938} }, wire = { red = {0.6875, 0.59375}, green = {0.6875, 0.71875} } },
  circuit_connector_sprites = get_circuit_connector_sprites({0.46875, 0.5}, {0.46875, 0.8125}, 26),
  circuit_wire_max_distance = 7.5,
  default_output_signal = "signal-A"
 },
 {
  type = "accumulator",
  name = "accu-4",
  icon = MODNAME.."/graphics/icons/accu-4.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "accu-4"},
  max_health = 600,
  corpse = "medium-remnants",
  collision_box = {{-0.9, -0.9}, {0.9, 0.9}},
  selection_box = {{-1, -1}, {1, 1}},
  energy_source =
  { type = "electric", buffer_capacity = "20MJ", usage_priority = "terciary", input_flow_limit = "1200kW", output_flow_limit = "1200kW" },
  picture = { filename = MODNAME.."/graphics/entitys/accu-4.png", priority = "extra-high", width = 124, height = 103, shift = {0.6875, -0.203125} },
  charge_animation = { filename = MODNAME.."/graphics/entitys/accu-charge-4.png", width = 138, height = 135, line_length = 8, frame_count = 24, shift = {0.46875, -0.640625}, animation_speed = 0.5 },
  charge_cooldown = 30,
  charge_light = {intensity = 0.3, size = 7},
  discharge_animation = { filename = MODNAME.."/graphics/entitys/accu-discharge-4.png", width = 147, height = 128, line_length = 8, frame_count = 24, shift = {0.390625, -0.53125}, animation_speed = 0.5 },
  discharge_cooldown = 60,
  discharge_light = {intensity = 0.7, size = 7},
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 5 },
  circuit_wire_connection_point = { shadow = { red = {0.984375, 1.10938}, green = {0.890625, 1.10938} }, wire = { red = {0.6875, 0.59375}, green = {0.6875, 0.71875} } },
  circuit_connector_sprites = get_circuit_connector_sprites({0.46875, 0.5}, {0.46875, 0.8125}, 26),
  circuit_wire_max_distance = 7.5,
  default_output_signal = "signal-A"
 },
 {
  type = "accumulator",
  name = "accu-5",
  icon = MODNAME.."/graphics/icons/accu-5.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "accu-5"},
  max_health = 750,
  corpse = "medium-remnants",
  collision_box = {{-0.9, -0.9}, {0.9, 0.9}},
  selection_box = {{-1, -1}, {1, 1}},
  energy_source =
  { type = "electric", buffer_capacity = "25MJ", usage_priority = "terciary", input_flow_limit = "1500kW", output_flow_limit = "1500kW" },
  picture = { filename = MODNAME.."/graphics/entitys/accu-5.png", priority = "extra-high", width = 124, height = 103, shift = {0.6875, -0.203125} },
  charge_animation = { filename = MODNAME.."/graphics/entitys/accu-charge-5.png", width = 138, height = 135, line_length = 8, frame_count = 24, shift = {0.46875, -0.640625}, animation_speed = 0.5 },
  charge_cooldown = 30,
  charge_light = {intensity = 0.3, size = 7},
  discharge_animation = { filename = MODNAME.."/graphics/entitys/accu-discharge-5.png", width = 147, height = 128, line_length = 8, frame_count = 24, shift = {0.390625, -0.53125}, animation_speed = 0.5 },
  discharge_cooldown = 60,
  discharge_light = {intensity = 0.7, size = 7},
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 5 },
  circuit_wire_connection_point = { shadow = { red = {0.984375, 1.10938}, green = {0.890625, 1.10938} }, wire = { red = {0.6875, 0.59375}, green = {0.6875, 0.71875} } },
  circuit_connector_sprites = get_circuit_connector_sprites({0.46875, 0.5}, {0.46875, 0.8125}, 26),
  circuit_wire_max_distance = 7.5,
  default_output_signal = "signal-A"
 },
 {
  type = "electric-pole",
  name = "medium-pole-2",
  icon = MODNAME.."/graphics/icons/medium-pole-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "medium-pole-2"},
  max_health = 200,
  corpse = "small-remnants",
  resistances = { { type = "fire", percent = 100 } },
  collision_box = {{-0.15, -0.15}, {0.15, 0.15}},
  selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
  drawing_box = {{-0.5, -2.8}, {0.5, 0.5}},
  maximum_wire_distance = 14,
  supply_area_distance = 7,
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  pictures = { filename = MODNAME.."/graphics/entitys/medium-pole-2.png", priority = "high", width = 136, height = 122, direction_count = 4, shift = {1.4, -1.0} },
  connection_points = { { shadow = { copper = {2.55, 0.4}, green = {2.0, 0.4}, red = {3.05, 0.4} }, wire = { copper = {-0.03125, -2.46875}, green = {-0.34375, -2.46875}, red = {0.25, -2.46875} } },
                { shadow = { copper = {2.9, 0.1}, green = {2.6, -0.15}, red = {3.25, 0.35} }, wire = { copper = {0.0625, -2.65625}, green = {-0.15625, -2.84375}, red = {0.28125, -2.5} } },
                { shadow = { copper = {1.5, -0.2}, green = {1.5, -0.55}, red = {1.5, 0.1} }, wire = { copper = {-0.4375, -2.28125}, green = {-0.4375, -2.5625}, red = {-0.4375, -2.0625} } },
                { shadow = { copper = {2.88, 0.2}, green = {3.2, -0.1}, red = {2.45, 0.4} }, wire = { copper = {-0.0625, -2.5625},  green = {0.15625, -2.75}, red = {-0.28125, -2.4375} } } },
  radius_visualisation_picture = { filename = "__base__/graphics/entity/small-electric-pole/electric-pole-radius-visualization.png", width = 12, height = 12, priority = "extra-high-no-scale" }
 },
 {
  type = "electric-pole",
  name = "medium-pole-3",
  icon = MODNAME.."/graphics/icons/medium-pole-3.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "medium-pole-3"},
  max_health = 300,
  corpse = "small-remnants",
  resistances = { { type = "fire", percent = 100 } },
  collision_box = {{-0.15, -0.15}, {0.15, 0.15}},
  selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
  drawing_box = {{-0.5, -2.8}, {0.5, 0.5}},
  maximum_wire_distance = 21,
  supply_area_distance = 10.5,
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  pictures = { filename = MODNAME.."/graphics/entitys/medium-pole-3.png", priority = "high", width = 136, height = 122, direction_count = 4, shift = {1.4, -1.0} },
  connection_points = { { shadow = { copper = {2.55, 0.4}, green = {2.0, 0.4}, red = {3.05, 0.4} }, wire = { copper = {-0.03125, -2.46875}, green = {-0.34375, -2.46875}, red = {0.25, -2.46875} } },
                { shadow = { copper = {2.9, 0.1}, green = {2.6, -0.15}, red = {3.25, 0.35} }, wire = { copper = {0.0625, -2.65625}, green = {-0.15625, -2.84375}, red = {0.28125, -2.5} } },
                { shadow = { copper = {1.5, -0.2}, green = {1.5, -0.55}, red = {1.5, 0.1} }, wire = { copper = {-0.4375, -2.28125}, green = {-0.4375, -2.5625}, red = {-0.4375, -2.0625} } },
                { shadow = { copper = {2.88, 0.2}, green = {3.2, -0.1}, red = {2.45, 0.4} }, wire = { copper = {-0.0625, -2.5625},  green = {0.15625, -2.75}, red = {-0.28125, -2.4375} } } },
  radius_visualisation_picture = { filename = "__base__/graphics/entity/small-electric-pole/electric-pole-radius-visualization.png", width = 12, height = 12, priority = "extra-high-no-scale" }
 },

 {
  type = "electric-pole",
  name = "big-pole-2",
  icon = MODNAME.."/graphics/icons/big-pole-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "big-pole-2"},
  max_health = 300,
  corpse = "medium-remnants",
  resistances = { { type = "fire", percent = 100 } },
  collision_box = {{-0.65, -0.65}, {0.65, 0.65}},
  selection_box = {{-1, -1}, {1, 1}},
  drawing_box = {{-1, -3}, {1, 0.5}},
  maximum_wire_distance = 60,
  supply_area_distance = 2,
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  pictures = { filename = "__base__/graphics/entity/big-electric-pole/big-electric-pole.png", priority = "high", width = 168, height = 165, direction_count = 4, shift = {1.6, -1.1} },
  connection_points = { { shadow = { copper = {2.7, 0}, green = {1.8, 0}, red = {3.6, 0} }, wire = { copper = {0, -3.125}, green = {-0.59375, -3.125}, red = {0.625, -3.125} } },
                { shadow = { copper = {3.1, 0.2}, green = {2.3, -0.3}, red = {3.8, 0.6} }, wire = { copper = {-0.0625, -3.125}, green = {-0.5, -3.4375}, red = {0.34375, -2.8125} } },
                { shadow = { copper = {2.9, 0.06}, green = {3.0, -0.6}, red = {3.0, 0.8} }, wire = { copper = {-0.09375, -3.09375}, green = {-0.09375, -3.53125}, red = {-0.09375, -2.65625} } },
                { shadow = { copper = {3.1, 0.2}, green = {3.8, -0.3}, red = {2.35, 0.6} }, wire = { copper = {-0.0625, -3.1875}, green = {0.375, -3.5}, red = {-0.46875, -2.90625} } } },
  radius_visualisation_picture = { filename = "__base__/graphics/entity/small-electric-pole/electric-pole-radius-visualization.png", width = 12, height = 12, priority = "extra-high-no-scale" },
 },
 {
  type = "electric-pole",
  name = "big-pole-3",
  icon = MODNAME.."/graphics/icons/big-pole-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "big-pole-3"},
  max_health = 450,
  corpse = "medium-remnants",
  resistances = { { type = "fire", percent = 100 } },
  collision_box = {{-0.65, -0.65}, {0.65, 0.65}},
  selection_box = {{-1, -1}, {1, 1}},
  drawing_box = {{-1, -3}, {1, 0.5}},
  maximum_wire_distance = 90,
  supply_area_distance = 2,
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  pictures = { filename = "__base__/graphics/entity/big-electric-pole/big-electric-pole.png", priority = "high", width = 168, height = 165, direction_count = 4, shift = {1.6, -1.1} },
  connection_points = { { shadow = { copper = {2.7, 0}, green = {1.8, 0}, red = {3.6, 0} }, wire = { copper = {0, -3.125}, green = {-0.59375, -3.125}, red = {0.625, -3.125} } },
                { shadow = { copper = {3.1, 0.2}, green = {2.3, -0.3}, red = {3.8, 0.6} }, wire = { copper = {-0.0625, -3.125}, green = {-0.5, -3.4375}, red = {0.34375, -2.8125} } },
                { shadow = { copper = {2.9, 0.06}, green = {3.0, -0.6}, red = {3.0, 0.8} }, wire = { copper = {-0.09375, -3.09375}, green = {-0.09375, -3.53125}, red = {-0.09375, -2.65625} } },
                { shadow = { copper = {3.1, 0.2}, green = {3.8, -0.3}, red = {2.35, 0.6} }, wire = { copper = {-0.0625, -3.1875}, green = {0.375, -3.5}, red = {-0.46875, -2.90625} } } },
  radius_visualisation_picture = { filename = "__base__/graphics/entity/small-electric-pole/electric-pole-radius-visualization.png", width = 12, height = 12, priority = "extra-high-no-scale" },
 },

 {
  type = "electric-pole",
  name = "substation-2",
  icon = MODNAME.."/graphics/icons/substation-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "substation-2"},
  max_health = 400,
  corpse = "medium-remnants",
  resistances = { { type = "fire", percent = 90 } },
  collision_box = {{-0.9, -0.9}, {0.9, 0.9}},
  selection_box = {{-1, -1}, {1, 1}},
  drawing_box = {{-1, -3}, {1, 1}},
  maximum_wire_distance = 28,
  supply_area_distance = 14,
  pictures = { filename = "__base__/graphics/entity/substation/substation.png", priority = "high", width = 132, height = 144, direction_count = 4, shift = {0.9, -1} },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/substation.ogg" }, apparent_volume = 1.5, audible_distance_modifier = 0.5, probability = 1 / (3 * 60) },
  connection_points = { { shadow = { copper = {1.9, -0.6}, green = {1.3, -0.6}, red = {2.65, -0.6} }, wire = { copper = {-0.25, -2.71875}, green = {-0.84375, -2.71875}, red = {0.34375, -2.71875} } },
                { shadow = { copper = {1.9, -0.6}, green = {1.2, -0.8}, red = {2.5, -0.35} }, wire = { copper = {-0.21875, -2.71875}, green = {-0.65625, -3.03125}, red = {0.1875, -2.4375} } },
                { shadow = { copper = {1.9, -0.6}, green = {1.9, -0.9}, red = {1.9, -0.3} }, wire = { copper = {-0.21875, -2.71875}, green = {-0.21875, -3.15625}, red = {-0.21875, -2.34375} } },
                { shadow = { copper = {1.8, -0.7}, green = {1.3, -0.6}, red = {2.4, -1.15} }, wire = { copper = {-0.21875, -2.75}, green = {-0.65625, -2.4375}, red = {0.1875, -3.03125} } } },
  radius_visualisation_picture = { filename = "__base__/graphics/entity/small-electric-pole/electric-pole-radius-visualization.png", width = 12, height = 12, priority = "extra-high-no-scale" },
 },
 {
  type = "electric-pole",
  name = "substation-3",
  icon = MODNAME.."/graphics/icons/substation-3.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "substation-3"},
  max_health = 600,
  corpse = "medium-remnants",
  resistances = { { type = "fire", percent = 90 } },
  collision_box = {{-0.9, -0.9}, {0.9, 0.9}},
  selection_box = {{-1, -1}, {1, 1}},
  drawing_box = {{-1, -3}, {1, 1}},
  maximum_wire_distance = 42,
  supply_area_distance = 21,
  pictures = { filename = "__base__/graphics/entity/substation/substation.png", priority = "high", width = 132, height = 144, direction_count = 4, shift = {0.9, -1} },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/substation.ogg" }, apparent_volume = 1.5, audible_distance_modifier = 0.5, probability = 1 / (3 * 60) },
  connection_points = { { shadow = { copper = {1.9, -0.6}, green = {1.3, -0.6}, red = {2.65, -0.6} }, wire = { copper = {-0.25, -2.71875}, green = {-0.84375, -2.71875}, red = {0.34375, -2.71875} } },
                { shadow = { copper = {1.9, -0.6}, green = {1.2, -0.8}, red = {2.5, -0.35} }, wire = { copper = {-0.21875, -2.71875}, green = {-0.65625, -3.03125}, red = {0.1875, -2.4375} } },
                { shadow = { copper = {1.9, -0.6}, green = {1.9, -0.9}, red = {1.9, -0.3} }, wire = { copper = {-0.21875, -2.71875}, green = {-0.21875, -3.15625}, red = {-0.21875, -2.34375} } },
                { shadow = { copper = {1.8, -0.7}, green = {1.3, -0.6}, red = {2.4, -1.15} }, wire = { copper = {-0.21875, -2.75}, green = {-0.65625, -2.4375}, red = {0.1875, -3.03125} } } },
  radius_visualisation_picture = { filename = "__base__/graphics/entity/small-electric-pole/electric-pole-radius-visualization.png", width = 12, height = 12, priority = "extra-high-no-scale" },
 },
 {
  type = "assembling-machine",
  name = "assembling-4",
  icon = MODNAME.."/graphics/icons/assembling-4.png",
  flags = {"placeable-neutral","placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "assembling-4"},
  max_health = 600,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  resistances = { { type = "fire", percent = 70 } },
  fluid_boxes = { { production_type = "input", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {0, -2} } } },
                  { production_type = "input", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {-0, 2} } } },
                  { production_type = "output", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = 1, pipe_connections = { { type = "output", position = {0, 2} } } },
                  off_when_no_fluid_recipe = true
                },
  open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
  close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { { filename = "__base__/sound/assembling-machine-t3-1.ogg", volume = 0.8 }, { filename = "__base__/sound/assembling-machine-t3-2.ogg", volume = 0.8 } },
                    idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 }, apparent_volume = 1.5,
                  },
  collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  fast_replaceable_group = "assembling-machine",
  animation = { filename = MODNAME.."/graphics/entitys/assembling-4.png", priority = "high", width = 142, height = 113, frame_count = 32, line_length = 8, shift = {0.84, -0.09} },
  crafting_categories = {"crafting", "advanced-crafting", "crafting-with-fluid"},
  crafting_speed = 1.75,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.03 / 3.5 },
  energy_usage = "400kW",
  ingredient_count = 10,
  module_specification = { module_slots = 6 }, allowed_effects = { "consumption", "speed", "productivity", "pollution" }
 },
 {
  type = "assembling-machine",
  name = "assembling-5",
  icon = MODNAME.."/graphics/icons/assembling-5.png",
  flags = {"placeable-neutral","placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "assembling-5"},
  max_health = 900,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  resistances = { { type = "fire", percent = 70 } },
  fluid_boxes = { { production_type = "input", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {0, -2} } } },
                  { production_type = "input", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {-0, 2} } } },
                  { production_type = "output", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = 1, pipe_connections = { { type = "output", position = {0, 2} } } },
                  off_when_no_fluid_recipe = true
                },
  open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
  close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { { filename = "__base__/sound/assembling-machine-t3-1.ogg", volume = 0.8 }, { filename = "__base__/sound/assembling-machine-t3-2.ogg", volume = 0.8 } },
                    idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 }, apparent_volume = 1.5,
                  },
  collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  fast_replaceable_group = "assembling-machine",
  animation = { filename = MODNAME.."/graphics/entitys/assembling-5.png", priority = "high", width = 142, height = 113, frame_count = 32, line_length = 8, shift = {0.84, -0.09} },
  crafting_categories = {"crafting", "advanced-crafting", "crafting-with-fluid", "extreme-crafting"},
  crafting_speed = 2.50,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.03 / 3.5 },
  energy_usage = "600kW",
  ingredient_count = 12,
  module_specification = { module_slots = 8 }, allowed_effects = { "consumption", "speed", "productivity", "pollution" }
 },
 {
  type = "assembling-machine",
  name = "assembling-6",
  icon = MODNAME.."/graphics/icons/assembling-6.png",
  flags = {"placeable-neutral","placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "assembling-6"},
  max_health = 2000,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  resistances = { { type = "fire", percent = 100 } },
  fluid_boxes = { { production_type = "input", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {0, -2} } } },
                  { production_type = "input", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {-0, 2} } } },
                  { production_type = "output", pipe_picture = assemblerpipepictures(), pipe_covers = pipecoverspictures(), base_area = 10, base_level = 1, pipe_connections = { { type = "output", position = {0, 2} } } },
                  off_when_no_fluid_recipe = true
                },
  open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
  close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { { filename = "__base__/sound/assembling-machine-t3-1.ogg", volume = 0.8 }, { filename = "__base__/sound/assembling-machine-t3-2.ogg", volume = 0.8 } },
                    idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 }, apparent_volume = 1.5,
                  },
  collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  fast_replaceable_group = "assembling-machine",
  animation = { filename = MODNAME.."/graphics/entitys/assembling-6.png", priority = "high", width = 142, height = 113, frame_count = 32, line_length = 8, shift = {0.84, -0.09} },
  crafting_categories = {"crafting", "advanced-crafting", "crafting-with-fluid", "extreme-crafting"},
  crafting_speed = 10,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.03 / 3.5 },
  energy_usage = "2000kW",
  ingredient_count = 20,
  module_specification = { module_slots = 10 }, allowed_effects = { "consumption", "speed", "productivity", "pollution" }
 },
 {
  type = "furnace",
  name = "e-furnace-2",
  icon = MODNAME.."/graphics/icons/e-furnace-2.png",
  flags = {"placeable-neutral", "placeable-player", "player-creation"},
  minable = {mining_time = 1, result = "e-furnace-2"},
  max_health = 300,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  light = {intensity = 1, size = 10},
  resistances = { { type = "fire", percent = 80 } },
  collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  module_specification = { module_slots = 4, module_info_icon_shift = {0, 0.8} },
  allowed_effects = {"consumption", "speed", "productivity", "pollution"},
  crafting_categories = {"smelting"},
  result_inventory_size = 2,
  crafting_speed = 4,
  energy_usage = "500kW",
  source_inventory_size = 1,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.005 },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/electric-furnace.ogg", volume = 0.7 }, apparent_volume = 1.5 },
  animation = { filename = MODNAME.."/graphics/entitys/e-furnace-2.png", priority = "high", width = 129, height = 100, frame_count = 1, shift = {0.421875, 0} },
  working_visualisations = { { animation = { filename = MODNAME.."/graphics/entitys/e-heater-2.png", priority = "high", width = 25, height = 15, frame_count = 12, animation_speed = 0.5, shift = {0.015625, 0.890625} }, light = {intensity = 0.4, size = 6, shift = {0.0, 1.0} } },
                             { animation = { filename = "__base__/graphics/entity/electric-furnace/electric-furnace-propeller-1.png", priority = "high", width = 19, height = 13, frame_count = 4, animation_speed = 0.5, shift = {-0.671875, -0.640625} } },
                             { animation = { filename = "__base__/graphics/entity/electric-furnace/electric-furnace-propeller-2.png", priority = "high", width = 12, height = 9, frame_count = 4, animation_speed = 0.5, shift = {0.0625, -1.234375} } }
                           },
  fast_replaceable_group = "furnace"
 },
 {
  type = "furnace",
  name = "e-furnace-3",
  icon = MODNAME.."/graphics/icons/e-furnace-3.png",
  flags = {"placeable-neutral", "placeable-player", "player-creation"},
  minable = {mining_time = 1, result = "e-furnace-3"},
  max_health = 500,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  light = {intensity = 1, size = 10},
  resistances = { { type = "fire", percent = 80 } },
  collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  module_specification = { module_slots = 10, module_info_icon_shift = {0, 0.8} },
  allowed_effects = {"consumption", "speed", "productivity", "pollution"},
  crafting_categories = {"smelting"},
  result_inventory_size = 5,
  crafting_speed = 10,
  energy_usage = "2000kW",
  source_inventory_size = 1,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.005 },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/electric-furnace.ogg", volume = 0.7 }, apparent_volume = 1.5 },
  animation = { filename = MODNAME.."/graphics/entitys/e-furnace-3.png", priority = "high", width = 129, height = 100, frame_count = 1, shift = {0.421875, 0} },
  working_visualisations = { { animation = { filename = MODNAME.."/graphics/entitys/e-heater-3.png", priority = "high", width = 25, height = 15, frame_count = 12, animation_speed = 0.5, shift = {0.015625, 0.890625} }, light = {intensity = 0.4, size = 6, shift = {0.0, 1.0} } },
                             { animation = { filename = "__base__/graphics/entity/electric-furnace/electric-furnace-propeller-1.png", priority = "high", width = 19, height = 13, frame_count = 4, animation_speed = 0.5, shift = {-0.671875, -0.640625} } },
                             { animation = { filename = "__base__/graphics/entity/electric-furnace/electric-furnace-propeller-2.png", priority = "high", width = 12, height = 9, frame_count = 4, animation_speed = 0.5, shift = {0.0625, -1.234375} } }
                           },
  fast_replaceable_group = "furnace"
 },
 {
  type = "assembling-machine",
  name = "chemical-2",
  icon = MODNAME.."/graphics/icons/chemical-2.png",
  flags = {"placeable-neutral","placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "chemical-2"},
  max_health = 600,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  collision_box = {{-1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  module_specification = { module_slots = 4 },
  allowed_effects = {"consumption", "speed", "productivity", "pollution"},
  animation = { north = { filename = MODNAME.."/graphics/entitys/chemical-2.png", width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} },
                west = { filename = MODNAME.."/graphics/entitys/chemical-2.png", x = 468, width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} },
                south = { filename = MODNAME.."/graphics/entitys/chemical-2.png", x = 312, width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} },
                east = { filename = MODNAME.."/graphics/entitys/chemical-2.png", x = 156, width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} }
              },
  working_visualisations = { { north_position = {0.94, -0.73}, west_position = {0.05, -1.46}, south_position = {-0.97, -1.47}, east_position = {-0.3, 0.02},
                               animation = { filename = MODNAME.."/graphics/entitys/boiling-2.png", frame_count = 35, width = 17, height = 12, animation_speed = 0.15 } },
                             { north_position = {1.4, -0.23}, west_position = {0.05, -0.96}, south_position = {-1, -1}, east_position = {-0.3, 0.55},
                               north_animation = { filename = MODNAME.."/graphics/entitys/boiling-window-2.png", frame_count = 1, width = 21, height = 10 },
                               east_animation = { filename = MODNAME.."/graphics/entitys/boiling-window-2.png", x = 21, frame_count = 1, width = 21, height = 10 },
                               south_animation = { filename = MODNAME.."/graphics/entitys/boiling-window-2.png", x = 42, frame_count = 1, width = 21, height = 10 } }
                           },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { { filename = "__base__/sound/chemical-plant.ogg", volume = 0.8 } }, idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 }, apparent_volume = 1.5, },
  crafting_speed = 2.5,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.03 / 3.5 },
  energy_usage = "500kW",
  ingredient_count = 6,
  crafting_categories = {"chemistry"},
  fluid_boxes = { { production_type = "input", pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {-1, -2} }} },
                  { production_type = "input", pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = { { type = "input", position = {1, -2} }} },
                  { production_type = "output", pipe_covers = pipecoverspictures(), base_level = 1, pipe_connections = {{ position = {-1, 2} }} },
                  { production_type = "output",  pipe_covers = pipecoverspictures(), base_level = 1, pipe_connections = {{ position = {1, 2} }} }
                }
 },
 {
  type = "assembling-machine",
  name = "chemical-3",
  icon = MODNAME.."/graphics/icons/chemical-3.png",
  flags = {"placeable-neutral","placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "chemical-3"},
  max_health = 900,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  collision_box = {{-1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  module_specification = { module_slots = 10 },
  allowed_effects = {"consumption", "speed", "productivity", "pollution"},
  animation = { north = { filename = MODNAME.."/graphics/entitys/chemical-3.png", width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} },
                west = { filename = MODNAME.."/graphics/entitys/chemical-3.png", x = 468, width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} },
                south = { filename = MODNAME.."/graphics/entitys/chemical-3.png", x = 312, width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} },
                east = { filename = MODNAME.."/graphics/entitys/chemical-3.png", x = 156, width = 156, height = 141, frame_count = 1, shift = {0.5, -0.078125} }
              },
  working_visualisations = { { north_position = {0.94, -0.73}, west_position = {0.05, -1.46}, south_position = {-0.97, -1.47}, east_position = {-0.3, 0.02},
                               animation = { filename = MODNAME.."/graphics/entitys/boiling-2.png", frame_count = 35, width = 17, height = 12, animation_speed = 0.15 } },
                             { north_position = {1.4, -0.23}, west_position = {0.05, -0.96}, south_position = {-1, -1}, east_position = {-0.3, 0.55},
                               north_animation = { filename = MODNAME.."/graphics/entitys/boiling-window-3.png", frame_count = 1, width = 21, height = 10 },
                               east_animation = { filename = MODNAME.."/graphics/entitys/boiling-window-3.png", x = 21, frame_count = 1, width = 21, height = 10 },
                               south_animation = { filename = MODNAME.."/graphics/entitys/boiling-window-3.png", x = 42, frame_count = 1, width = 21, height = 10 } }
                           },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { { filename = "__base__/sound/chemical-plant.ogg", volume = 0.8 } }, idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 }, apparent_volume = 1.5, },
  crafting_speed = 10,
  energy_source = { type = "electric", usage_priority = "secondary-input", emissions = 0.03 / 3.5 },
  energy_usage = "2000kW",
  ingredient_count = 10,
  crafting_categories = {"chemistry"},
  fluid_boxes = { { production_type = "input", pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = {{ type="input", position = {-1, -2} }} },
                  { production_type = "input", pipe_covers = pipecoverspictures(), base_area = 10, base_level = -1, pipe_connections = {{ type="input", position = {1, -2} }} },
                  { production_type = "output", pipe_covers = pipecoverspictures(), base_level = 1, pipe_connections = {{ position = {-1, 2} }} },
                  { production_type = "output",  pipe_covers = pipecoverspictures(), base_level = 1, pipe_connections = {{ position = {1, 2} }} }
                }
 },
 {
  type = "radar",
  name = "radar-2",
  icon = MODNAME.."/graphics/icons/radar-2.png",
  flags = {"placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "radar-2"},
  max_health = 300,
  corpse = "big-remnants",
  resistances = { { type = "fire", percent = 70 } },
  collision_box = {{-1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
  energy_per_sector = "20MJ",
  max_distance_of_sector_revealed = 100,
  max_distance_of_nearby_sector_revealed = 10,
  energy_per_nearby_scan = "500kJ",
  energy_source = { type = "electric", usage_priority = "secondary-input" },
  energy_usage = "600kW",
  pictures = { filename = MODNAME.."/graphics/entitys/radar-2.png", priority = "low", width = 153, height = 131, apply_projection = false, direction_count = 64, line_length = 8, shift = {0.875, -0.34375} },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { { filename = "__base__/sound/radar.ogg" } }, apparent_volume = 2, }
 },
 {
  type = "mining-drill",
  name = "mining-2",
  icon = MODNAME.."/graphics/icons/mining-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {mining_time = 1, result = "mining-2"},
  max_health = 600,
  resource_categories = {"basic-solid"},
  corpse = "big-remnants",
  collision_box = {{ -1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{ -1.5, -1.5}, {1.5, 1.5}},
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/electric-mining-drill.ogg", volume = 0.75 }, apparent_volume = 1.5, },
  animations = { north = { priority = "extra-high", width = 110, height = 114, line_length = 8, shift = {0.2, -0.2}, filename = MODNAME.."/graphics/entitys/mining-n-2.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" },
                 east = { priority = "extra-high", width = 129, height = 100, line_length = 8, shift = {0.45, 0}, filename = MODNAME.."/graphics/entitys/mining-e-2.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" },
                 south = { priority = "extra-high", width = 109, height = 111, line_length = 8, shift = {0.15, 0}, filename = MODNAME.."/graphics/entitys/mining-s-2.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" },
                 west = { priority = "extra-high", width = 128, height = 100, line_length = 8, shift = {0.25, 0}, filename = MODNAME.."/graphics/entitys/mining-w-2.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" }
               },
  mining_speed = 2.5,
  energy_source = { type = "electric", emissions = 0.15 / 1.5, usage_priority = "secondary-input" },
  energy_usage = "300kW",
  mining_power = 6,
  resource_searching_radius = 10,
  vector_to_place_result = {0, -1.85},
  module_specification = { module_slots = 6 },
  radius_visualisation_picture = { filename = MODNAME.."/graphics/entitys/mining-visualization.png", width = 12, height = 12 },
  fast_replaceable_group = "mining-drill"
 },
 {
  type = "mining-drill",
  name = "mining-3",
  icon = MODNAME.."/graphics/icons/mining-3.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {mining_time = 1, result = "mining-3"},
  max_health = 1000,
  resource_categories = {"basic-solid"},
  corpse = "big-remnants",
  collision_box = {{ -1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{ -1.5, -1.5}, {1.5, 1.5}},
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/electric-mining-drill.ogg", volume = 0.75 }, apparent_volume = 1.5, },
  animations = { north = { priority = "extra-high", width = 110, height = 114, line_length = 8, shift = {0.2, -0.2}, filename = MODNAME.."/graphics/entitys/mining-n-3.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" },
                 east = { priority = "extra-high", width = 129, height = 100, line_length = 8, shift = {0.45, 0}, filename = MODNAME.."/graphics/entitys/mining-e-3.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" },
                 south = { priority = "extra-high", width = 109, height = 111, line_length = 8, shift = {0.15, 0}, filename = MODNAME.."/graphics/entitys/mining-s-3.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" },
                 west = { priority = "extra-high", width = 128, height = 100, line_length = 8, shift = {0.25, 0}, filename = MODNAME.."/graphics/entitys/mining-w-3.png", frame_count = 64, animation_speed = 0.5, run_mode = "forward-then-backward" }
               },
  mining_speed = 10,
  energy_source = { type = "electric", emissions = 0.15 / 1.5, usage_priority = "secondary-input" },
  energy_usage = "2000kW",
  mining_power = 20,
  resource_searching_radius = 100,
  vector_to_place_result = {0, -1.85},
  module_specification = { module_slots = 10 },
  radius_visualisation_picture = { filename = MODNAME.."/graphics/entitys/mining-visualization.png", width = 12, height = 12 },
  fast_replaceable_group = "mining-drill"
 },
 {
  type = "mining-drill",
  name = "pumpjack-2",
  icon = MODNAME.."/graphics/icons/pumpjack-2.png",
  flags = {"placeable-neutral", "player-creation"},
  minable = {mining_time = 1, result = "pumpjack-2"},
  resource_categories = {"basic-fluid"},
  max_health = 300,
  corpse = "big-remnants",
  dying_explosion = "medium-explosion",
  collision_box = {{ -1.4, -1.4}, {1.4, 1.4}},
  selection_box = {{ -1.5, -1.5}, {1.5, 1.5}},
  drawing_box = {{-1.6, -2.5}, {1.5, 1.6}},
  energy_source = { type = "electric", emissions = 0.15 / 1.5, usage_priority = "secondary-input" },
  fluid_box = { base_area = 1, base_level = 1, pipe_covers = pipecoverspictures(), pipe_connections = { { positions = { {1, -2}, {2, -1}, {-1, 2}, {-2, 1} } } } },
  energy_usage = "200kW",
  mining_speed = 3,
  mining_power = 2,
  resource_searching_radius = 0.49,
  vector_to_place_result = {0, 0},
  module_specification = { module_slots = 5 },
  radius_visualisation_picture = { filename = MODNAME.."/graphics/entitys/mining-visualization.png", width = 12, height = 12 },
  base_picture = { sheet = { filename = MODNAME.."/graphics/entitys/pumpjack-base-2.png", priority = "extra-high", width = 114, height = 113, shift = {0.1875, -0.03125} } },
  animations = { north = { priority = "extra-high", width = 116, height = 110, line_length = 10, shift = {0.125, -0.71875}, filename = MODNAME.."/graphics/entitys/pumpjack-ani-2.png", frame_count = 40, animation_speed = 0.5 } },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/pumpjack.ogg" }, apparent_volume = 1.5, },
  fast_replaceable_group = "pumpjack"
 },
 {
  type = "roboport",
  name = "roboport-2",
  icon = MODNAME.."/graphics/icons/roboport-2.png",
  flags = {"placeable-player", "player-creation"},
  minable = {hardness = 0.2, mining_time = 0.5, result = "roboport-2"},
  max_health = 1500,
  corpse = "big-remnants",
  collision_box = {{-1.7, -1.7}, {1.7, 1.7}},
  selection_box = {{-2, -2}, {2, 2}},
  dying_explosion = "medium-explosion",
  energy_source = { type = "electric", usage_priority = "secondary-input", input_flow_limit = "15MW", buffer_capacity = "500MJ" },
  recharge_minimum = "40MJ",
  energy_usage = "150kW",
  charging_energy = "5000kW",
  logistics_radius = 75,
  construction_radius = 150,
  charge_approach_distance = 5,
  robot_slots_count = 21,
  material_slots_count = 21,
  stationing_offset = {0, 0},
  charging_offsets = { {-1.5, -0.5}, {1.5, -0.5}, {1.5, 1.5}, {-1.5, 1.5} },
  base = { filename = MODNAME.."/graphics/entitys/roboport-base-2.png", width = 143, height = 135, shift = {0.5, 0.25} },
  base_patch = { filename = MODNAME.."/graphics/entitys/roboport-patch-2.png", priority = "medium", width = 69, height = 50, frame_count = 1, shift = {0.03125, 0.203125} },
  base_animation = { filename = "__base__/graphics/entity/roboport/roboport-base-animation.png", priority = "medium", width = 42, height = 31, frame_count = 8, animation_speed = 0.5, shift = {-0.5315, -1.9375} },
  door_animation_up = { filename = "__base__/graphics/entity/roboport/roboport-door-up.png", priority = "medium", width = 52, height = 20, frame_count = 16, shift = {0.015625, -0.890625} },
  door_animation_down = { filename = "__base__/graphics/entity/roboport/roboport-door-down.png", priority = "medium", width = 52, height = 22, frame_count = 16, shift = {0.015625, -0.234375} },
  recharging_animation = { filename = "__base__/graphics/entity/roboport/roboport-recharging.png", priority = "high", width = 37, height = 35, frame_count = 16, scale = 1.5, animation_speed = 0.5 },
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { sound = { filename = "__base__/sound/roboport-working.ogg", volume = 0.6 }, max_sounds_per_type = 3, audible_distance_modifier = 0.5, probability = 1 / (5 * 60) },
  recharging_light = {intensity = 0.4, size = 5},
  request_to_open_door_timeout = 15,
  spawn_and_station_height = -0.1,
  draw_logistic_radius_visualization = true,
  draw_construction_radius_visualization = true,
  open_door_trigger_effect = { { type = "play-sound", sound = { filename = "__base__/sound/roboport-door.ogg", volume = 1.2 } } },
  close_door_trigger_effect = { { type = "play-sound", sound = { filename = "__base__/sound/roboport-door.ogg", volume = 0.75 } } },
  circuit_wire_connection_point = { wire = { red = {0.78125, 1.375}, green = {0.78125, 1.53125} },
                                    shadow = { red = {1.17188, 1.98438}, green = {1.04688, 2.04688} }
                                  },
  circuit_connector_sprites = get_circuit_connector_sprites({0.59375, 1.3125}, nil, 18),
  circuit_wire_max_distance = 7.5,
  default_available_logistic_output_signal = "signal-X",
  default_total_logistic_output_signal = "signal-Y",
  default_available_construction_output_signal = "signal-Z",
  default_total_construction_output_signal = "signal-T",
 },
 {
  type = "construction-robot",
  name = "consti-2",
  icon = MODNAME.."/graphics/icons/consti-2.png",
  flags = {"placeable-player", "player-creation", "placeable-off-grid", "not-on-map"},
  minable = {hardness = 0.1, mining_time = 0.1, result = "consti-2"},
  resistances = { { type = "fire", percent = 85 } },
  max_health = 500,
  collision_box = {{0, 0}, {0, 0}},
  selection_box = {{-0.5, -1.5}, {0.5, -0.5}},
  max_payload_size = 5,
  speed = 0.5,
  transfer_distance = 1,
  max_energy = "5MJ",
  energy_per_tick = "0.05kJ",
  speed_multiplier_when_out_of_energy = 0.2,
  energy_per_move = "10kJ",
  min_to_charge = 0.2,
  max_to_charge = 0.95,
  working_light = {intensity = 0.8, size = 3},
  idle = { filename = MODNAME.."/graphics/entitys/consti-2.png", priority = "high", line_length = 16, width = 32, height = 36, frame_count = 1, shift = {0, -0.15625}, direction_count = 16 },
  in_motion = { filename = MODNAME.."/graphics/entitys/consti-2.png", priority = "high", line_length = 16, width = 32, height = 36, frame_count = 1, shift = {0, -0.15625}, direction_count = 16, y = 36 },
  shadow_idle = { filename = "__base__/graphics/entity/construction-robot/construction-robot-shadow.png", priority = "high", line_length = 16, width = 50, height = 24, frame_count = 1, shift = {1.09375, 0.59375}, direction_count = 16 },
  shadow_in_motion = { filename = "__base__/graphics/entity/construction-robot/construction-robot-shadow.png", priority = "high", line_length = 16, width = 50, height = 24, frame_count = 1, shift = {1.09375, 0.59375}, direction_count = 16 },
  working = { filename = MODNAME.."/graphics/entitys/consti-working-2.png", priority = "high", line_length = 2, width = 28, height = 36, frame_count = 2, shift = {0, -0.15625}, direction_count = 16, animation_speed = 0.3 },
  shadow_working = { stripes = util.multiplystripes( 2, { { filename = "__base__/graphics/entity/construction-robot/construction-robot-shadow.png", width_in_frames = 16, height_in_frames = 1 } } ),
                     priority = "high", width = 50, height = 24, frame_count = 2, shift = {1.09375, 0.59375}, direction_count = 16 },
  smoke = { filename = "__base__/graphics/entity/smoke-construction/smoke-01.png", width = 39, height = 32, frame_count = 19, line_length = 19, shift = {0.078125, -0.15625}, animation_speed = 0.3 },
  sparks = { { filename = "__base__/graphics/entity/sparks/sparks-01.png", width = 39, height = 34, frame_count = 19, line_length = 19, shift = {-0.109375, 0.3125}, tint = { r = 1.0, g = 0.9, b = 0.0, a = 1.0 }, animation_speed = 0.3 },
             { filename = "__base__/graphics/entity/sparks/sparks-02.png", width = 36, height = 32, frame_count = 19, line_length = 19, shift = {0.03125, 0.125}, tint = { r = 1.0, g = 0.9, b = 0.0, a = 1.0 }, animation_speed = 0.3 },
             { filename = "__base__/graphics/entity/sparks/sparks-03.png", width = 42, height = 29, frame_count = 19, line_length = 19, shift = {-0.0625, 0.203125}, tint = { r = 1.0, g = 0.9, b = 0.0, a = 1.0 }, animation_speed = 0.3 },
             { filename = "__base__/graphics/entity/sparks/sparks-04.png", width = 40, height = 35, frame_count = 19, line_length = 19, shift = {-0.0625, 0.234375}, tint = { r = 1.0, g = 0.9, b = 0.0, a = 1.0 }, animation_speed = 0.3 },
             { filename = "__base__/graphics/entity/sparks/sparks-05.png", width = 39, height = 29, frame_count = 19, line_length = 19, shift = {-0.109375, 0.171875}, tint = { r = 1.0, g = 0.9, b = 0.0, a = 1.0 }, animation_speed = 0.3 },
             { filename = "__base__/graphics/entity/sparks/sparks-06.png", width = 44, height = 36, frame_count = 19, line_length = 19, shift = {0.03125, 0.3125}, tint = { r = 1.0, g = 0.9, b = 0.0, a = 1.0 }, animation_speed = 0.3 }
           },
  working_sound = flying_robot_sounds(),
  cargo_centered = {0.0, 0.2},
  construction_vector = {0.30, 0.22},
 },
 {
  type = "logistic-robot",
  name = "logi-2",
  icon = MODNAME.."/graphics/icons/logi-2.png",
  flags = {"placeable-player", "player-creation", "placeable-off-grid", "not-on-map"},
  minable = {hardness = 0.1, mining_time = 0.1, result = "logi-2"},
  resistances = { { type = "fire", percent = 85 } },
  max_health = 500,
  collision_box = {{0, 0}, {0, 0}},
  selection_box = {{-0.5, -1.5}, {0.5, -0.5}},
  max_payload_size = 5,
  speed = 0.5,
  transfer_distance = 1,
  max_energy = "5MJ",
  energy_per_tick = "0.05kJ",
  speed_multiplier_when_out_of_energy = 0.2,
  energy_per_move = "10kJ",
  min_to_charge = 0.2,
  max_to_charge = 0.95,
  idle = { filename = MODNAME.."/graphics/entitys/logi-2.png", priority = "high", line_length = 16, width = 41, height = 42, frame_count = 1, shift = {0.015625, -0.09375}, direction_count = 16, y = 42 },
  idle_with_cargo = { filename = MODNAME.."/graphics/entitys/logi-2.png", priority = "high", line_length = 16,  width = 41, height = 42, frame_count = 1, shift = {0.015625, -0.09375}, direction_count = 16 },
  in_motion = { filename = MODNAME.."/graphics/entitys/logi-2.png", priority = "high", line_length = 16, width = 41, height = 42, frame_count = 1, shift = {0.015625, -0.09375}, direction_count = 16, y = 126 },
  in_motion_with_cargo = { filename = MODNAME.."/graphics/entitys/logi-2.png", priority = "high", line_length = 16, width = 41, height = 42, frame_count = 1, shift = {0.015625, -0.09375}, direction_count = 16, y = 84 },
  shadow_idle = { filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png", priority = "high", line_length = 16, width = 59, height = 23, frame_count = 1, shift = {0.96875, 0.609375}, direction_count = 16, y = 23 },
  shadow_idle_with_cargo = { filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png", priority = "high", line_length = 16, width = 59, height = 23, frame_count = 1, shift = {0.96875, 0.609375}, direction_count = 16 },
  shadow_in_motion = { filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png", priority = "high", line_length = 16, width = 59, height = 23, frame_count = 1, shift = {0.96875, 0.609375}, direction_count = 16, y = 23 },
  shadow_in_motion_with_cargo = { filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png", priority = "high", line_length = 16, width = 59, height = 23, frame_count = 1, shift = {0.96875, 0.609375}, direction_count = 16 },
  working_sound = flying_robot_sounds(),
  cargo_centered = {0.0, 0.2}
 },
 {
  type = "inserter",
  name = "alien-inserter",
  icon = MODNAME.."/graphics/icons/alien-inserter.png",
  flags = {"placeable-neutral", "placeable-player", "player-creation"},
  minable = { hardness = 0.2, mining_time = 0.5, result = "alien-inserter" },
  max_health = 400, 
  corpse = "small-remnants", 
  resistances = { { type = "fire", percent = 90 } },
  collision_box = {{-0.15, -0.15}, {0.15, 0.15}},
  selection_box = {{-0.4, -0.35}, {0.4, 0.45}},
  pickup_position = {0, -1},
  insert_position = {0, 1.2},
  energy_per_movement = 14000,
  energy_per_rotation = 14000,
  energy_source = { type = "electric", usage_priority = "secondary-input", drain = "100kW" },
  extension_speed = 0.25,
  rotation_speed = 0.25,
  fast_replaceable_group = "inserter",
  vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
  working_sound = { match_progress_to_activity = true,
                    sound = { { filename = "__base__/sound/inserter-fast-1.ogg", volume = 0.75 },
                              { filename = "__base__/sound/inserter-fast-2.ogg", volume = 0.75 },
                              { filename = "__base__/sound/inserter-fast-3.ogg", volume = 0.75 },
                              { filename = "__base__/sound/inserter-fast-4.ogg", volume = 0.75 },
                              { filename = "__base__/sound/inserter-fast-5.ogg", volume = 0.75 }
                            }
                  },
  hand_base_picture = { filename = MODNAME.."/graphics/entitys/alien-inserter-hand-base.png", priority = "extra-high", width = 8, height = 34 },
  hand_closed_picture = { filename = MODNAME.."/graphics/entitys/alien-inserter-hand-closed.png", priority = "extra-high", width = 18, height = 41 },
  hand_open_picture = { filename = MODNAME.."/graphics/entitys/alien-inserter-hand-open.png", priority = "extra-high", width = 18, height = 41 },
  hand_base_shadow = { filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png", priority = "extra-high", width = 8, height = 34 },
  hand_closed_shadow = { filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed-shadow.png", priority = "extra-high", width = 18, height = 41 },
  hand_open_shadow = { filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open-shadow.png", priority = "extra-high", width = 18, height = 41 },
  platform_picture = { sheet = { filename = MODNAME.."/graphics/entitys/alien-inserter-platform.png", priority = "extra-high", width = 46, height = 46, shift = {0.09375, 0} } },
  circuit_wire_connection_point = { shadow = { red = {-0.1875, 0.21875}, green = {-0.1875, 0.25}, }, wire = { red = {-0.375, 0.03125}, green = {-0.375, 0.0625} } },
  circuit_connector_sprites = { connector_main = { filename = "__base__/graphics/entity/circuit-connector/circuit-connector-inserter-main.png", priority = "low", width = 15, height = 12, shift = {-0.203125 + 0, 0.125 + -0.09375} },
                                connector_shadow = { filename = "__base__/graphics/entity/circuit-connector/circuit-connector-inserter-shadow.png", priority = "low", width = 18, height = 18, shift = {-0.03125 + 0, 0.1875 + -0.09375} },
                                led_red = { filename = "__base__/graphics/entity/circuit-connector/circuit-connector-inserter-led-red.png", priority = "low", width = 6, height = 5, shift = {-0.15625 + 0, 0.171875 + -0.09375} },
                                led_green = { filename = "__base__/graphics/entity/circuit-connector/circuit-connector-inserter-led-green.png", priority = "low", width = 6, height = 5, shift = {-0.15625 + 0, 0.171875 + -0.09375} },
                                led_blue = { filename = "__base__/graphics/entity/circuit-connector/circuit-connector-inserter-led-blue.png", priority = "low", width = 5, height = 5, shift = {-0.265625 + 0, 0.078125 + -0.09375} },
                                logistic_animation =  { filename = "__base__/graphics/entity/circuit-connector/circuit-connector-logistic-animation.png", priority = "low", blend_mode = "additive", line_length = 4, width = 43, height = 43, frame_count = 15, shift = {0.015625 - 0.265625 + 0, -0.234375 + 0.078125 + -0.09375} },
                                led_light = { intensity = 0.8, size = 0.9, },
                                blue_led_light_offset = {-0.28125, -0.03125},
                                red_green_led_light_offset = {-0.15625, 0.0625},
                              },
  circuit_wire_max_distance = 7.5
 }
}
) 